version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gokselmanav-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gokselmanav_db
      POSTGRES_USER: gokselmanav_user
      POSTGRES_PASSWORD: gokselmanav_password_2024
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/backups:/backups
    networks:
      - gokselmanav-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gokselmanav_user -d gokselmanav_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gokselmanav-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gokselmanav.com
      PGADMIN_DEFAULT_PASSWORD: admin_password_2024
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - gokselmanav-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  gokselmanav-network:
    driver: bridge 